// moves.js
export const MOVES = {
  // ───── 랭크 전용 기술 ─────
  "칼춤":     { power: 0, type: "노말", accuracy: 100, alwaysHit: true, effect: null,
                rank: { atk: 2, turns: 2 } },
  "코튼가드": { power: 0, type: "노말", accuracy: 100, alwaysHit: true, effect: null,
                rank: { def: 2, turns: 2 } },
  "고속이동": { power: 0, type: "노말", accuracy: 100, alwaysHit: true, effect: null,
                rank: { spd: 2, turns: 2 } },
  "명상":     { power: 0, type: "에스퍼", accuracy: 100, alwaysHit: true, effect: null,
                rank: { atk: 1, def: 1, turns: 2 } },
  "벌크업":   { power: 0, type: "격투", accuracy: 100, alwaysHit: true, effect: null,
                rank: { atk: 1, def: 1, turns: 2 } },
  "용의춤":   { power: 0, type: "드래곤", accuracy: 100, alwaysHit: true, effect: null,
                rank: { atk: 1, spd: 1, turns: 2 } },

  // ───── 노말 ─────
  "전광석화":   { power: 30, type: "노말", accuracy: 100, alwaysHit: true,  effect: null },
  "힘껏치기":   { power: 50, type: "노말", accuracy: 75,  alwaysHit: false, effect: null },
  "베어가르기": { power: 45, type: "노말", accuracy: 100, alwaysHit: false, effect: null, highCrit: true },
  "신속":       { power: 50, type: "노말", accuracy: 100, alwaysHit: true,  effect: null },
  "돌림노래":   { power: 40, type: "노말", accuracy: 100, alwaysHit: false, effect: null },
  "탐내기":     { power: 40, type: "노말", accuracy: 100, alwaysHit: false, effect: null },
  "스피드스타": { power: 35, type: "노말", accuracy: 100, alwaysHit: true,  effect: null, aoeEnemy: true },
  "할퀴기":     { power: 30, type: "노말", accuracy: 100, alwaysHit: false, effect: null },
  "몸통박치기": { power: 30, type: "노말", accuracy: 100, alwaysHit: false, effect: null },
  "하이퍼보이스":{ power: 50, type: "노말", accuracy: 100, alwaysHit: false, effect: null, aoeEnemy: true },
  "속이기":     { power: 30, type: "노말", accuracy: 70,  alwaysHit: false, effect: null, fakeOut: true },
  "성장":       { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: null,
                  rank: { atk: 1, turns: 2 } },
  "야금야금":   { power: 40, type: "노말", accuracy: 100, alwaysHit: false, skipEvasion: true, effect: null },
  "박치기":     { power: 40, type: "노말", accuracy: 100, alwaysHit: false,
                  effect: { chance: 0.3, volatile: "풀죽음" } },
  "울음소리":   { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: null,
                  rank: { targetAtk: -1, turns: 2 }, aoeEnemy: true },
  "눈물그렁그렁":{ power: 0, type: "노말", accuracy: 100, alwaysHit: false, effect: null,
                  rank: { targetAtk: -1, turns: 2 } },
  "째려보기":   { power: 0,  type: "노말", accuracy: 100, alwaysHit: false, effect: null,
                  rank: { targetDef: -1, turns: 2 }, aoeEnemy: true },
  "싫은소리":   { power: 0,  type: "노말", accuracy: 85,  alwaysHit: false, effect: null,
                  rank: { targetDef: -2, turns: 2 } },
  "비축하기":   { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: null,
                  rank: { def: 2, turns: 2 } },
  "꼬리흔들기": { power: 0,  type: "노말", accuracy: 100, alwaysHit: false, effect: null,
                  rank: { targetDef: -1, turns: 2 }, aoeEnemy: true },
  "웅크리기":   { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: null,
                  rank: { def: 1, turns: 2 } },
  "단단해지기": { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: null,
                  rank: { def: 1, turns: 2 } },
  "그림자분신": { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: null,
                  rank: { spd: 1, turns: 2 } },
  "분발":       { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: null,
                  rank: { atk: 1, turns: 2 } },
  "비밀이야기": { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: null,
                  rank: { targetAtk: -1, turns: 2 } },
  "뽐내기":     { power: 0,  type: "노말", accuracy: 85,  alwaysHit: false,
                  rank: { targetAtk: 2, turns: 3 }, effect: { chance: 1, volatile: "혼란" } },
  "뱀눈초리":   { power: 0,  type: "노말", accuracy: 90,  alwaysHit: false, targetSelf: false,
                  effect: { chance: 1, status: "마비" } },
  "누르기":     { power: 50, type: "노말", accuracy: 90,  alwaysHit: false, targetSelf: false,
                  effect: { chance: 0.3, status: "마비" } },
  "소닉붐":     { power: 1,  type: "노말", accuracy: 90,  alwaysHit: false,
                  effect: null, fixedDamage: 40 },
  "튀어오르기": { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: null, splash: true, targetSelf: true },
  "파괴광선":   { power: 70, type: "노말", accuracy: 90,  alwaysHit: false, effect: null, hyperBeam: true },
  "소란피기":   { power: 50, type: "노말", accuracy: 100, alwaysHit: false, effect: null,
                  outrage: { confusion: false, minTurn: 2, maxTurn: 5, powers: [50, 45, 40, 40, 40] } },
  "더블윙":     { power: 30, type: "비행", accuracy: 90,  alwaysHit: false, effect: null,
                  multiHit: { min: 2, max: 2 } },
  "고속스핀":   { power: 40, type: "노말", accuracy: 100, alwaysHit: false, effect: null,
                  rapidSpin: true, rank: { spd: 1, turns: 3 } },
  "울트라메가튀어오르기": { power: 0, type: "노말", accuracy: 100, alwaysHit: true, effect: null, divineStrike: true, targetSelf: true },
  "아침햇살":           { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,
                      effect: { heal: { default: 0.25, "쾌청": 0.3, "비": 0.2, "싸라기눈": 0.2, "모래바람": 0.2 } }, targetSelf: true },

  // ───── 불 ─────
  "화염바퀴":       { power: 40, type: "불", accuracy: 100, alwaysHit: false, effect: { chance: 0.1, status: "화상" } },
  "불꽃엄니":       { power: 40, type: "불", accuracy: 95, alwaysHit: false, effect: { chance: 0.1, status: "화상" } },
  "블레이즈킥":     { power: 50, type: "불", accuracy: 90, alwaysHit: false, effect: { chance: 0.1, status: "화상" }, highCrit: true },
  "니트로차지":     { power: 40, type: "불", accuracy: 100, alwaysHit: false, effect: null, rank: { spd: 1, turns: 3 } },
  "불꽃세례":       { power: 30, type: "불", accuracy: 100, alwaysHit: false, effect: { chance: 0.1, status: "화상", thawEnemy: true } },
  "도깨비불":       { power: 0,  type: "불", accuracy: 85,  alwaysHit: false, targetSelf: false, effect: { chance: 1, status: "화상" } },
  "열풍":           { power: 50, type: "불", accuracy: 90, alwaysHit: false, effect: { chance: 0.1, status: "화상" }, aoeEnemy: true },
  "불대문자":       { power: 60, type: "불", accuracy: 85,  alwaysHit: false, effect: null },
  "매지컬플레임":   { power: 45, type: "불", accuracy: 100, alwaysHit: false, effect: null,
                      rank: { targetAtk: -1, turns: 2 } },
  "불꽃채찍":   { power: 60, type: "불", accuracy: 100, alwaysHit: false, effect: null,
                      rank: { targetDef: -1, turns: 2 } },
  "불꽃춤":   { power: 50, type: "불", accuracy: 100, alwaysHit: false, effect: null,
                      rank: { chance:0.5, atk: 1, turns: 3 } },
  "불꽃튀기기":     { power: 40, type: "불", accuracy: 100, alwaysHit: false, effect: null, sparks: true  },
  "화염방사":       { power: 50, type: "불", accuracy: 100, alwaysHit: false, effect: { chance: 0.1, status: "화상" } },
  "회오리불꽃":     { power: 35, type: "불", accuracy: 85,  alwaysHit: false, effect: null, trap: true },
  "열사의대지":     { power: 50, type: "땅", accuracy: 100, alwaysHit: false, effect: { chance: 0.3, status: "화상" } },
  "플레어드라이브": { power: 70, type: "불", accuracy: 100, alwaysHit: false, effect: { recoil: 0.33, chance: 0.1, status: "화상" } },
  "오버히트":   { power: 70, type: "불", accuracy: 100, alwaysHit: false, effect: null, targetSelf:true, rank: { atk: -1, turns: 3 } },
  "플레어송":   { power: 50, type: "불", accuracy: 100, alwaysHit: false, effect: null, rank: { atk: 1, turns: 3 } },
  "원념의칼":     { power: 55, type: "불", accuracy: 100, alwaysHit: false, effect: { drain: 0.15 } },

  // ───── 물 ─────
  "거품광선":   { power: 40, type: "물", accuracy: 100, alwaysHit: false, effect: null },
  "아쿠아테일":   { power: 50, type: "물", accuracy: 90, alwaysHit: false, effect: null },
  "껍질에숨기": { power: 0,  type: "물", accuracy: 100, alwaysHit: true,  targetSelf: true, effect: null,
                  rank: { def: 1, turns: 2 } },
  "거품":       { power: 40, type: "물", accuracy: 100, alwaysHit: false, effect: null, aoeEnemy: true },
  "파도타기":   { power: 40, type: "물", accuracy: 100, alwaysHit: false, effect: null, aoe: true },
  "물대포":     { power: 30, type: "물", accuracy: 100, alwaysHit: false, effect: null },
  "아쿠아제트": { power: 30, type: "물", accuracy: 100, alwaysHit: true,  effect: null },
  "하이드로펌프":{ power: 60, type: "물", accuracy: 80,  alwaysHit: false, effect: null },
  "물의파동":   { power: 40, type: "물", accuracy: 100, alwaysHit: false, effect: { chance: 0.2, volatile: "혼란" } },
  "열탕":       { power: 50, type: "물", accuracy: 100, alwaysHit: false, effect: { chance: 0.3, status: "화상" } },
  "셸블레이드": { power: 45, type: "물", accuracy: 95,  alwaysHit: false, effect: null,
                  rank: { chance: 0.5, targetDef: -1, turns: 2 } },
  "아쿠아링":   { power: 0,  type: "물", accuracy: 100, alwaysHit: true,  effect: null, aquaRing: true, targetSelf: true },
  "해수스파우팅":{ power: 70, type: "물", accuracy: 100, alwaysHit: false, effect: null, waterspout: true, aoeEnemy: true },
  "퀵턴":       { power: 40, type: "물", accuracy: 100, alwaysHit: false, effect: null, uTurn: true },
  "폭포오르기": { power: 50, type: "물", accuracy: 100, alwaysHit: false, effect: { chance: 0.2, volatile: "풀죽음" } },
  "아쿠아브레이크":{ power: 50, type: "물", accuracy: 100, alwaysHit: false, effect: null,
                    rank: { chance: 0.2, targetDef: -1, turns: 2 } },
  "탁류":       { power: 50, type: "물", accuracy: 85,  alwaysHit: false, targetSelf: false, effect: null,
                  rank: { chance: 0.3, targetSpd: -1, turns: 3 }, aoeEnemy: true },
  "퀵턴": { power: 40, type: "물", accuracy: 100, alwaysHit: false,
          effect: null, uTurn: true },
  "집게해머":         { power: 50, type: "물", accuracy: 95, alwaysHit: false, effect: null, highCrit: true },
  "물수리검":   { power: 15, type: "물", accuracy: 100, alwaysHit: false, effect: null,
                  multiHit: { min: 2, max: 5 } },

  // ───── 전기 ─────
  "번개펀치":     { power: 45, type: "전기", accuracy: 100, alwaysHit: false, effect: { chance: 0.1, status: "마비" } },
  "10만볼트":     { power: 50, type: "전기", accuracy: 100, alwaysHit: false, effect: { chance: 0.3, status: "마비" } },
  "방전":         { power: 50, type: "전기", accuracy: 100, alwaysHit: false, effect: { chance: 0.3, status: "마비" }, aoe: true },
  "번개":         { power: 60, type: "전기", accuracy: 70,  alwaysHit: false, effect: { chance: 0.3, status: "마비" },
                    weatherAlwaysHit: ["비"] },
  "전기쇼크":     { power: 30, type: "전기", accuracy: 100, alwaysHit: false, effect: { chance: 0.1, status: "마비" } },
  "전기자석파":   { power: 0,  type: "전기", accuracy: 90,  alwaysHit: false, targetSelf: false,
                    effect: { chance: 1, status: "마비" } },
  "볼부비부비":   { power: 30, type: "전기", accuracy: 100, alwaysHit: false, targetSelf: false,
                    effect: { chance: 1, status: "마비" } },
  "전자포":       { power: 60, type: "전기", accuracy: 50,  alwaysHit: false, targetSelf: false,
                    effect: { chance: 1, status: "마비" } },
  "충전":         { power: 0,  type: "전기", accuracy: 100, alwaysHit: true,  targetSelf: true, effect: null,
                    charge: true, rank: { def: 1, turns: 2 } },
  "번개엄니":     { power: 40, type: "전기", accuracy: 95,  alwaysHit: false, effect: { chance: 0.1, status: "마비" } },
  "잠재댄스":     { power: 50, type: "전기", accuracy: 100, alwaysHit: false, effect: null },
  "일렉트릭네트": { power: 40, type: "전기", accuracy: 95,  alwaysHit: false, targetSelf: false, effect: null,
                    rank: { targetSpd: -1, turns: 3 }, aoeEnemy: true },
  "볼트체인지":   { power: 40, type: "전기", accuracy: 100, alwaysHit: false, effect: null, uTurn: true },
  "찌리리따끔따끔":   { power: 50, type: "전기", accuracy: 100, alwaysHit: false, effect: { chance: 0.3, volatile: "풀죽음" } },

  // ───── 풀 ─────
  "에너지볼":       { power: 40, type: "풀", accuracy: 100, alwaysHit: false, effect: null,
                      rank: { chance: 0.1, targetDef: -1, turns: 2 } },
  "솔라빔":         { power: 40, type: "풀", accuracy: 100, alwaysHit: false, effect: null },
  "파워휩":         { power: 70, type: "풀", accuracy: 85, alwaysHit: false, effect: null },
  "솔라블레이드": { power: 60, type: "풀", accuracy: 100, alwaysHit: false, effect: null, solarBlade: true },
  "나뭇잎":         { power: 30, type: "풀", accuracy: 100, alwaysHit: false, effect: null },
  "잎날가르기":     { power: 40, type: "풀", accuracy: 95,  alwaysHit: false, effect: null, highCrit: true, aoeEnemy: true },
  "씨폭탄":         { power: 40, type: "풀", accuracy: 100, alwaysHit: false, effect: null },
  "성장":           { power: 0,  type: "풀", accuracy: 100, alwaysHit: true,  targetSelf: true, effect: null,
                      rank: { atk: 1, turns: 2 } },
  "흡수":           { power: 30, type: "풀", accuracy: 100, alwaysHit: false, effect: { drain: 0.15 } },
  "메가드레인":     { power: 30, type: "풀", accuracy: 100, alwaysHit: false, effect: { drain: 0.15 } },
  "기가드레인":     { power: 45, type: "풀", accuracy: 100, alwaysHit: false, effect: { drain: 0.15 } },
  "매지컬리프":     { power: 40, type: "풀", accuracy: 100, alwaysHit: true,  effect: null },
  "하바네로엑기스": { power: 0,  type: "풀", accuracy: 100, alwaysHit: true,  targetSelf: false, effect: null,
                      rank: { targetAtk: 2, targetDef: -2, turns: 2 } },
  "저리가루":       { power: 0,  type: "풀", accuracy: 75,  alwaysHit: false, targetSelf: false,
                      effect: { chance: 1, status: "마비" }, poisonPowder: true },
  "꽃잎댄스":       { power: 60, type: "풀", accuracy: 100, alwaysHit: false, effect: null,
                      outrage: { confusion: true, minTurn: 2, maxTurn: 3, powers: [60, 45, 30] } },
  "니들가드":       { power: 0,  type: "풀", accuracy: 100, alwaysHit: true,  targetSelf: true, effect: null, spikyShield: true },
  "리프블레이드":   { power: 50, type: "풀", accuracy: 100, alwaysHit: false, effect: null, highCrit: true },
  "우드혼":         { power: 45, type: "풀", accuracy: 100, alwaysHit: false, effect: { drain: 0.15 } },
  "사과산":         { power: 50, type: "풀", accuracy: 100, alwaysHit: false, effect: null,
                      rank: { targetDef: -1, turns: 2 } },
  "트릭플라워": { power: 40, type: "풀", accuracy: 100, alwaysHit: true, effect: null, alwaysCrit: true },
  "광합성":           { power: 0,  type: "풀", accuracy: 100, alwaysHit: true,
                      effect: { heal: { default: 0.25, "쾌청": 0.3, "비": 0.2, "싸라기눈": 0.2, "모래바람": 0.2 } }, targetSelf: true },
  "휘적휘적포":       { power: 50, type: "풀", accuracy: 90, alwaysHit: false, effect: { drain: 0.15, chance: 0.2, status: "화상" } },
  "힘흡수":           { power: 0,  type: "풀", accuracy: 100, alwaysHit: false, effect: null, strengthSap: 6,
                        targetSelf: false, rank: { targetAtk: -1, turns: 2 } },
  // ───── 얼음 ─────
  "눈보라":         { power: 40, type: "얼음", accuracy: 70,  alwaysHit: false, effect: { chance: 0.1, status: "얼음" }, aoeEnemy: true },
  "얼음뭉치":       { power: 35, type: "얼음", accuracy: 100, alwaysHit: true,  effect: null },
  "냉동빔":         { power: 50, type: "얼음", accuracy: 100, alwaysHit: false, effect: { chance: 0.1, status: "얼음" } },
  "냉동펀치":       { power: 45, type: "얼음", accuracy: 100, alwaysHit: false, effect: { chance: 0.1, status: "얼음" } },
  "얼어붙은바람":   { power: 40, type: "얼음", accuracy: 95,  alwaysHit: false, targetSelf: false, effect: null,
                      rank: { targetSpd: -1, turns: 3 }, aoeEnemy: true },
  "아이스스피너":     { power: 50, type: "얼음", accuracy: 100, alwaysHit: false, effect: null },
  "얼음엄니":       { power: 40, type: "얼음", accuracy: 100, alwaysHit: false, effect: { chance: 0.1, status: "얼음" } },
  "눈싸라기":       { power: 30, type: "얼음", accuracy: 100, alwaysHit: false, effect: { chance: 0.1, status: "얼음" }, aoeEnemy: true },
  "눈사태":         { power: 40, type: "얼음", accuracy: 100, alwaysHit: false, effect: null, avalanche: true },
  "흑안개":         { power: 0,  type: "얼음", accuracy: 100, alwaysHit: true,  effect: null, haze: true, targetSelf: true },

  // ───── 격투 ─────
  "인파이트":           { power: 60, type: "격투", accuracy: 100, alwaysHit: false, targetSelf: true, effect: null,
                          rank: { def: -1, turns: 2 } },
  "파동탄":             { power: 40, type: "격투", accuracy: 100, alwaysHit: true,  effect: null },
  "기합구슬":             { power: 60, type: "격투", accuracy: 70, alwaysHit: false,  effect: null, rank: { chance: 0.1, targetDef: -1, turns: 2 }   },
  "깨트리기":           { power: 50, type: "격투", accuracy: 100, alwaysHit: false, effect: null, breakBarrier: true },
  "그로우펀치": { power: 30, type: "격투", accuracy: 100, alwaysHit: false, effect: null, rank: { atk: 1, turns: 2} },
  "드레인펀치":         { power: 45, type: "격투", accuracy: 100, alwaysHit: false, effect: { drain: 0.15 } },
  "바디프레스":         { power: 50, type: "격투", accuracy: 100, alwaysHit: false, effect: null, bodyPress: true },
  "무릎차기":           { power: 70, type: "격투", accuracy: 90,  alwaysHit: false, effect: null, jumpKick: true },
  "진공파":             { power: 35, type: "격투", accuracy: 100, alwaysHit: true,  effect: null },
   "발경":         { power: 40, type: "격투", accuracy: 100, alwaysHit: false, effect: { chance: 0.3, status: "마비" } },
   "성스러운칼": { power: 50, type: "격투", accuracy: 100, alwaysHit: false, skipEvasion: true, ignoreDefRank: true, effect: null },
   "리벤지": { power: 40, type: "격투", accuracy: 100, comeback: true },
  "3연화살":           { power: 60, type: "격투", accuracy: 100, alwaysHit: false,
                          effect: { chance: 0.3, volatile: "풀죽음" }, rank: { chance: 0.5, targetDef: -1, turns: 2 } },

  // ───── 독 ─────
  "용해액":   { power: 30, type: "독", accuracy: 100, alwaysHit: false, effect: null,
                rank: { chance: 0.1, targetDef: -1, turns: 2 }, aoeEnemy: true },
  "독침":     { power: 30, type: "독", accuracy: 100, alwaysHit: false, effect: { chance: 0.3, status: "독" } },
  "독찌르기": { power: 50, type: "독", accuracy: 100, alwaysHit: false, effect: { chance: 0.3, status: "독" } },
  "독가루":   { power: 0,  type: "독", accuracy: 75,  alwaysHit: false, targetSelf: false,
                effect: { chance: 1, status: "독" }, poisonPowder: true },
  "오물폭탄": { power: 50, type: "독", accuracy: 100, alwaysHit: false, effect: { chance: 0.3, status: "독" } },
  "오물웨이브":{ power: 50, type: "독", accuracy: 100, alwaysHit: false, effect: { chance: 0.1, status: "독" }, aoe: true },
  "맹독":     { power: 0,  type: "독", accuracy: 90,  alwaysHit: false, targetSelf:false, effect: { chance: 1, status: "독" } },
  "독가스":     { power: 0,  type: "독", accuracy: 90,  alwaysHit: false, targetSelf:false, effect: { chance: 1, status: "독" } },
  "똬리틀기": { power: 0,  type: "독", accuracy: 100, alwaysHit: true,  targetSelf: true, effect: null,
                rank: { atk: 1, def: 1, spd: 1, turns: 3 } },
  "베놈쇼크": { power: 50, type: "독", accuracy: 100, alwaysHit: false, effect: null, venomShock: true },
  "녹기": { power: 0, type: "독", accuracy: 100, alwaysHit: true, effect: null,
                rank: { def: 2, turns: 2 } },
  "킬러스핀":   { power: 40, type: "독", accuracy: 100, alwaysHit: false, effect: null,
                  rapidSpin: true, rank: { spd: 1, turns: 3 }, effect: { chance: 1, status: "독" } },

  // ───── 땅 ─────
  "지진":       { power: 50, type: "땅", accuracy: 100, alwaysHit: false, effect: null, aoe: true },
  "땅고르기":   { power: 40, type: "땅", accuracy: 100, alwaysHit: false, effect: null,
                  rank: { targetSpd: -1, turns: 3 }, aoe: true },
  "모래뿌리기": { power: 0,  type: "땅", accuracy: 100, alwaysHit: false, targetSelf: false, effect: null,
                  rank: { targetSpd: -1, turns: 3 } },
  "진흙뿌리기": { power: 30, type: "땅", accuracy: 100, alwaysHit: false, targetSelf: false, effect: null,
                  rank: { targetSpd: -1, turns: 3 } },
  "머드샷":     { power: 40, type: "땅", accuracy: 95,  alwaysHit: false, targetSelf: false, effect: null,
                  rank: { targetSpd: -1, turns: 3 } },
  "대지의힘":   { power: 50, type: "땅", accuracy: 100, alwaysHit: false, effect: null,
                  rank: { chance: 0.1, targetDef: -1, turns: 2 } },
  "드릴라이너": { power: 50, type: "땅", accuracy: 95,  alwaysHit: false, effect: null, highCrit: true },
  "구멍파기":   { power: 50, type: "땅", accuracy: 1,   alwaysHit: false, effect: null, dig: true },

  // ───── 바위 ─────
  "스톤에지":   { power: 40, type: "바위", accuracy: 80,  alwaysHit: false, effect: null },
  "돌떨구기":   { power: 40, type: "바위", accuracy: 90,  alwaysHit: false, effect: null },
  "바위깨기":   { power: 30, type: "바위", accuracy: 80,  alwaysHit: false, effect: null,
                  rank: { targetDef: -1, turns: 3 } },
  "파워젬":     { power: 50, type: "바위", accuracy: 100,  alwaysHit: false, effect: null },
  "록블라스트": { power: 40, type: "바위", accuracy: 90,  alwaysHit: false, effect: null },
  "원시의힘":   { power: 40, type: "바위", accuracy: 100, alwaysHit: false, effect: null,
                  rank: { chance: 0.1, atk: 1, def: 1, spd: 1, turns: 3 } },
  "스톤샤워":   { power: 45, type: "바위", accuracy: 90,  alwaysHit: false, effect: { chance: 0.3, volatile: "풀죽음" }, aoeEnemy: true },
  "암석봉인":   { power: 40, type: "바위", accuracy: 95,  alwaysHit: false, effect: null, rank: { targetSpd: -1, turns: 3 } },

  // ───── 비행 ─────
  "에어슬래시": { power: 40, type: "비행", accuracy: 95,  alwaysHit: false, effect: { chance: 0.3, volatile: "풀죽음" } },
  "애크러뱃":   { power: 45, type: "비행", accuracy: 100, alwaysHit: false, effect: null },
  "열풍비행":   { power: 40, type: "비행", accuracy: 100, alwaysHit: false, effect: { chance: 0.1, status: "화상" } },
  "쪼기":       { power: 40, type: "비행", accuracy: 100, alwaysHit: false, effect: null },
  "날개치기":   { power: 40, type: "비행", accuracy: 100, alwaysHit: false, effect: null },
  "회전부리":   { power: 50, type: "비행", accuracy: 100, alwaysHit: false, effect: null },
  "제비반환":   { power: 45, type: "비행", accuracy: 100, alwaysHit: true,  effect: null },
  "공중날기":   { power: 50, type: "비행", accuracy: 95,  alwaysHit: false, effect: null, fly: true },
  "에어커터":   { power: 40, type: "비행", accuracy: 95,  alwaysHit: false, effect: null, highCrit: true, aoeEnemy: true },
  "브레이브버드":{ power: 70, type: "비행", accuracy: 100, alwaysHit: false, effect: { recoil: 0.33 } },
  "폭풍":       { power: 60, type: "비행", accuracy: 70,  alwaysHit: false, effect: { chance: 0.3, volatile: "혼란" },
                  weatherAlwaysHit: ["비"], weatherAccuracy: { "쾌청": 50 } },
  "날개쉬기": { power: 0, type: "비행", accuracy: 100, alwaysHit: true,
              effect: { removeFlying: true, heal: 0.22 }, targetSelf: true },

  // ───── 에스퍼 ─────
  "사이코키네시스": { power: 50, type: "에스퍼", accuracy: 100, alwaysHit: false, effect: null,
                      rank: { chance: 0.1, targetDef: -1, turns: 2 } },
  "망각술":         { power: 0,  type: "에스퍼", accuracy: 100, alwaysHit: true,  effect: null,
                      rank: { chance: 1, def: 2, turns: 2 } },
  "사이코쇼크":     { power: 50, type: "에스퍼", accuracy: 100, alwaysHit: false, effect: null },
  "염동력":         { power: 40, type: "에스퍼", accuracy: 100, alwaysHit: false,
                      effect: { chance: 0.1, volatile: "혼란" } },
  "사념의박치기":   { power: 50, type: "에스퍼", accuracy: 100, alwaysHit: false,
                      effect: { chance: 0.2, volatile: "풀죽음" } },
  "빛의장막":       { power: 0,  type: "에스퍼", accuracy: 100, alwaysHit: true,  effect: null,
                      lightScreen: true, targetSelf: true },
  "리플렉터":       { power: 0,  type: "에스퍼", accuracy: 100, alwaysHit: true,  effect: null,
                      lightScreen: true, targetSelf: true },
  "어시스트파워":   { power: 30, type: "에스퍼", accuracy: 100, alwaysHit: false, effect: null, assistPower: true },
  "회복봉인":       { power: 0,  type: "에스퍼", accuracy: 100, alwaysHit: true,  effect: null,
                      healBlock: true, targetSelf: false, aoeEnemy: true },
  "미래예지":       { power: 70, type: "에스퍼", accuracy: 100, alwaysHit: true,  effect: null, futureSight: true },
  "사이코팽":       { power: 50, type: "에스퍼", accuracy: 100, alwaysHit: false, effect: null, breakBarrier: true },

  // ───── 벌레 ─────
  "덤벼들기":   { power: 50, type: "벌레", accuracy: 100, alwaysHit: false,
                  rank: { targetAtk: -1, turns: 3 } },
  "실뿜기":     { power: 0,  type: "벌레", accuracy: 95,  alwaysHit: false,
                  rank: { targetSpd: -2, turns: 3 }, aoeEnemy: true },
  "벌레먹음":   { power: 40, type: "벌레", accuracy: 100, alwaysHit: false, effect: null },
  "흡혈":       { power: 50, type: "벌레", accuracy: 100, alwaysHit: false, effect: { drain: 0.15 } },
  "꽃가루경단": { power: 50, type: "벌레", accuracy: 100, alwaysHit: false, effect: null, pollenPuff: true },
  "연속자르기": { power: 30, type: "벌레", accuracy: 95,  alwaysHit: false, effect: null, furyCutter: true },
  "유턴":       { power: 40, type: "벌레", accuracy: 100, alwaysHit: false, effect: null, uTurn: true },
  "시그널빔":   { power: 45, type: "벌레", accuracy: 100, alwaysHit: false,
                  effect: { chance: 0.1, volatile: "혼란" } },
  "하드롤러":   { power: 40, type: "벌레", accuracy: 100, alwaysHit: false,
                  effect: { chance: 0.3, volatile: "풀죽음" } },
  "나비춤":     { power: 0,  type: "벌레", accuracy: 100, alwaysHit: true,  effect: null,
                  rank: { atk: 1, def: 1, spd: 1, turns: 3 } },
  "벌레의야단법석":{ power: 50, type: "벌레", accuracy: 100, alwaysHit: false, effect: null,
                    targetSelf: false, rank: { chance: 0.1, targetDef: 1, turns: 2 } },
  "시저크로스": { power: 50, type: "벌레", accuracy: 100, alwaysHit: false,  effect: null },
  "엄습하는일격":   { power: 40,  type: "벌레", accuracy: 90, alwaysHit: false,  effect: null,
                  rank: { targetAtk: -1, turns: 2 } },
  // ───── 고스트 ─────
  "섀도볼":     { power: 50, type: "고스트", accuracy: 100, alwaysHit: false, effect: null,
                  rank: { chance: 0.2, targetDef: -1, turns: 3 } },
  "섀도크루":   { power: 55, type: "고스트", accuracy: 100, alwaysHit: false, effect: null, highCrit: true },
  "나이트헤드": { power: 40, type: "고스트", accuracy: 100, alwaysHit: true,  effect: null },
  "섀도스니크": { power: 40, type: "고스트", accuracy: 100, alwaysHit: false, effect: null },
  "이상한빛":   { power: 0,  type: "고스트", accuracy: 100, alwaysHit: false,
                  effect: { chance: 1, volatile: "혼란" } },
  "핥기":       { power: 30, type: "고스트", accuracy: 100, alwaysHit: false,
                  effect: { chance: 0.3, status: "마비" } },
  "야습":       { power: 45, type: "고스트", accuracy: 100, alwaysHit: true,  effect: null },
  "기습":       { power: 45, type: "고스트", accuracy: 100, alwaysHit: true,  effect: null },
  "놀래키기":   { power: 30, type: "고스트", accuracy: 100, alwaysHit: false,
                  effect: { chance: 0.3, volatile: "풀죽음" } },
  "괴상한바람": { power: 40, type: "고스트", accuracy: 100, alwaysHit: false, effect: null,
                  rank: { chance: 0.1, spd: 1, def: 1, atk: 1, turns: 3 } },
  "저주":       { power: 0,  type: "고스트", accuracy: 100, alwaysHit: true,  effect: null, curse: true },
  "고스트다이브":{ power: 50, type: "고스트", accuracy: 100, alwaysHit: false, effect: null, ghostDive: true },

  // ───── 드래곤 ─────
  "드래곤크루":   { power: 50, type: "드래곤", accuracy: 100, alwaysHit: false, effect: null },
  "드래곤다이브": { power: 50, type: "드래곤", accuracy: 75,  alwaysHit: false,
                    effect: { chance: 0.2, volatile: "풀죽음" } },
  "용의숨결":     { power: 40, type: "드래곤", accuracy: 75,  alwaysHit: false,
                    effect: { chance: 0.3, status: "마비" } },
  "용의파동":     { power: 50, type: "드래곤", accuracy: 100, alwaysHit: false, effect: null },
  "용의분노":     { power: 1,  type: "드래곤", accuracy: 100, alwaysHit: false,
                    effect: null, fixedDamage: 40 },
  "자이로볼":     { power: 30, type: "강철",   accuracy: 100, alwaysHit: false, effect: null, gyroBall: true },
  "회오리":       { power: 30, type: "드래곤", accuracy: 100, alwaysHit: false,
                    effect: { chance: 0.2, volatile: "풀죽음" }, twister: true, aoeEnemy: true },
  "역린":         { power: 60, type: "드래곤", accuracy: 100, alwaysHit: false, effect: null,
                    outrage: { confusion: true, minTurn: 2, maxTurn: 3, powers: [60, 45, 30] } },
  "용성군":       { power: 60, type: "드래곤", accuracy: 90,  alwaysHit: false, effect: null,
                    rank: { atk: -2, turns: 2 } },

  // ───── 악 ─────
  "악의파동":     { power: 50, type: "악", accuracy: 100, alwaysHit: false,
                    effect: { chance: 0.2, volatile: "풀죽음" } },
  "속여때리기":   { power: 40, type: "악", accuracy: 100, alwaysHit: true,  effect: null },
  "물기":         { power: 40, type: "악", accuracy: 100, alwaysHit: false,
                    effect: { chance: 0.3, volatile: "풀죽음" } },
  "탁쳐서떨구기":   { power: 50, type: "악", accuracy: 100, alwaysHit: false, effect: null },
  "도각참":   { power: 60, type: "악", accuracy: 100, alwaysHit: true, effect: null },
  "세차게휘두르기":{ power: 40, type: "악", accuracy: 100, alwaysHit: false, effect: null, aoe: true },
  "바크아웃":     { power: 40,  type: "악", accuracy: 95,  alwaysHit: false, effect: null,
                    rank: { targetAtk: -1, turns: 3 }, aoeEnemy: true },
  "거짓울음":     { power: 0,  type: "악", accuracy: 100, alwaysHit: false, effect: null,
                    rank: { targetDef: -2, turns: 2 } },
  "나쁜음모":     { power: 0,  type: "악", accuracy: 100, alwaysHit: true,  effect: null,
                    rank: { atk: 2, turns: 2 } },
  "승부굳히기":   { power: 40, type: "악", accuracy: 100, alwaysHit: false, effect: null, finisher: true },
  "깨물어부수기": { power: 50, type: "악", accuracy: 100, alwaysHit: false, effect: null,
                    rank: { chance: 0.2, targetAtk: -1, turns: 2 } },
  "지옥찌르기":   { power: 50, type: "악", accuracy: 100, alwaysHit: false, effect: null, throatChop: true },
  "트집":         { power: 0,  type: "악", accuracy: 100, alwaysHit: false, effect: null, torment: true, targetSelf: false },
  "추억의선물":   { power: 0,  type: "악", accuracy: 100, alwaysHit: true,  effect: null, memento: true, targetSelf: false },
  "도발":         { power: 0,  type: "악", accuracy: 100, alwaysHit: false, effect: null, taunt: true, targetSelf: false },
  "깜짝베기":   { power: 50, type: "악", accuracy: 100, alwaysHit: false, effect: null, highCrit: true },

  // ───── 강철 ─────
  "아이언테일": { power: 50, type: "강철", accuracy: 75,  alwaysHit: false, effect: null,
                  rank: { chance: 0.3, targetDef: -1, turns: 3 } },
  "아이언헤드": { power: 50, type: "강철", accuracy: 100,  alwaysHit: false,
                  effect: { chance: 0.3, volatile: "풀죽음" } },
  "메탈크로우": { power: 40, type: "강철", accuracy: 95,  alwaysHit: false, effect: null,
                  rank: { chance: 0.1, atk: 1, turns: 3 } },
  "코멧펀치":   { power: 50, type: "강철", accuracy: 90,  alwaysHit: false, effect: null,
                  rank: { chance: 0.2, atk: 1, turns: 3 } },
  "러스터캐논": { power: 50, type: "강철", accuracy: 100, alwaysHit: false, effect: null,
                  rank: { chance: 0.1, targetAtk: -1, turns: 2 } },
  "불릿펀치":   { power: 40, type: "강철", accuracy: 100, alwaysHit: false, effect: null },
  "플래시캐논": { power: 40, type: "강철", accuracy: 100, alwaysHit: true,  effect: null },
  "철제광선":   { power: 90, type: "강철", accuracy: 95,  alwaysHit: false, effect: { recoilMaxHp: 0.5 } },
  "강철날개":   { power: 50, type: "강철", accuracy: 100, alwaysHit: false,
                  effect: { chance: 0.1, def: 1, turns: 3 } },
  "금속음":     { power: 0,  type: "강철", accuracy: 85,  alwaysHit: false, effect: null,
                  rank: { targetDef: -2, turns: 2 } },
  "철벽":       { power: 0,  type: "강철", accuracy: 85,  alwaysHit: true,  effect: null,
                  rank: { def: 2, turns: 2 } },

  // ───── 페어리 ─────
  "문포스":         { power: 40, type: "페어리", accuracy: 100, alwaysHit: false, effect: null },
  "요정의바람":     { power: 30, type: "페어리", accuracy: 100, alwaysHit: false, effect: null },
  "치근거리기":     { power: 50, type: "페어리", accuracy: 90,  alwaysHit: false, effect: null,
                      rank: { chance: 0.1, targetAtk: -1, turns: 2 } },
  "차밍보이스":     { power: 35, type: "페어리", accuracy: 100, alwaysHit: true,  effect: null, aoeEnemy: true },
  "매지컬샤인":     { power: 50, type: "페어리", accuracy: 100, alwaysHit: false, effect: null, aoeEnemy: true },
  "드레인키스":     { power: 40, type: "페어리", accuracy: 100, alwaysHit: false, effect: { drain: 0.22 } },
  "애교부리기":     { power: 0,  type: "페어리", accuracy: 100, alwaysHit: false, targetSelf: false, effect: null,
                      rank: { targetAtk: -2, turns: 2 } },
  "초롱초롱눈동자": { power: 0,  type: "페어리", accuracy: 100, alwaysHit: true,  targetSelf: false, effect: null,
                      rank: { targetAtk: -1, turns: 2 } },
  "달빛":           { power: 0,  type: "페어리", accuracy: 100, alwaysHit: true,
                      effect: { heal: { default: 0.25, "쾌청": 0.3, "비": 0.2, "싸라기눈": 0.2, "모래바람": 0.2 } }, targetSelf: true },
  "매혹의보이스":   { power: 50, type: "페어리", accuracy: 100, alwaysHit: false, effect: null, enchantedVoice: true },

  // ───── 날씨 ─────
  "쾌청":     { power: 0, type: "불",   accuracy: 100, alwaysHit: true, effect: { weather: "쾌청",    weatherTurns: 5 } },
  "비바라기": { power: 0, type: "물",   accuracy: 100, alwaysHit: true, effect: { weather: "비",       weatherTurns: 5 } },
  "모래바람": { power: 0, type: "바위", accuracy: 100, alwaysHit: true, effect: { weather: "모래바람", weatherTurns: 5 } },
  "싸라기눈": { power: 0, type: "얼음", accuracy: 100, alwaysHit: true, effect: { weather: "싸라기눈", weatherTurns: 5 } },

  // ───── 장판 ─────
  "스텔스록": { power: 0, type: "바위", accuracy: 100, alwaysHit: true,
                effect: null, field: "stealth_rock", targetSelf: false, aoeEnemy: true },
  "독압정":   { power: 0, type: "독",   accuracy: 100, alwaysHit: true,
                effect: null, field: "toxic_spikes", targetSelf: false, aoeEnemy: true },
  "암석액스": { power: 50, type: "바위", accuracy: 90,  alwaysHit: false,
                effect: null, field: "stealth_rock" },

  // ───── 특수 기술 ─────
  "방어":       { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: null, defend: true, targetSelf: true },
  "판별":       { power: 0,  type: "격투", accuracy: 100, alwaysHit: true,  effect: null, defend: true, targetSelf: true },
  "울부짖기":   { power: 0,  type: "노말", accuracy: 100, alwaysHit: false, effect: null, roar: true, targetSelf: false },
  "날려버리기":   { power: 0,  type: "노말", accuracy: 100, alwaysHit: false, effect: null, roar: true, targetSelf: false },
  "원수갚기":   { power: 40, type: "노말", accuracy: 100, alwaysHit: false, effect: null, revenge: true },
  "뒀다쓰기":   { power: 70, type: "노말", accuracy: 100, alwaysHit: false, effect: null, lastResort: true },
  "신비의부적": { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: null, amulet: true, targetSelf: true },
  "클리어스모그":{ power: 40, type: "독",  accuracy: 100, alwaysHit: true,  effect: null, clearSmog: true },
  "구르기":     { power: 30, type: "바위", accuracy: 90,  alwaysHit: false, effect: null, rollout: true },
  "태만함":     { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: { heal: 0.22 }, targetSelf: true },
  "HP회복":     { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: { heal: 0.22 }, targetSelf: true },
  "게으름피우기":     { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: { heal: 0.22 }, targetSelf: true },
  "알낳기":     { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: { heal: 0.22 }, targetSelf: true },
  "우유마시기":     { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: { heal: 0.22 }, targetSelf: true },
  "생명의물방울":{ power: 0, type: "물",   accuracy: 100, alwaysHit: true,  effect: { heal: 0.25 }, targetSelf: true },
  "희망사항":   { power: 0,  type: "노말", accuracy: 100, alwaysHit: true,  effect: null, wish: true, targetSelf: true },
  "속임수":     { power: 50, type: "악",   accuracy: 100, alwaysHit: false, effect: null, trickster: true },
  "이판사판태클":{ power: 70, type: "노말", accuracy: 100, alwaysHit: false, effect: { recoil: 0.33 } },
  "웨이브태클":{ power: 70, type: "물", accuracy: 100, alwaysHit: false, effect: { recoil: 0.33 } },
  "돌진":       { power: 50, type: "노말", accuracy: 85,  alwaysHit: false, effect: { recoil: 0.25 } },
  "보복":       { power: 50, type: "악",   accuracy: 100, alwaysHit: false, effect: null, avalanche: true },
  "마구찌르기": { power: 1,  type: "노말", accuracy: 85,  alwaysHit: false, effect: null,
                  multiHit: { min: 2, max: 5, fixedDamage: 10 } },
  "드래곤애로": { power: 1,  type: "드래곤", accuracy: 85,  alwaysHit: false, effect: null,
                  multiHit: { min: 2, max: 2, fixedDamage: 30 } },
  "고드름침": { power: 1,  type: "얼음", accuracy: 100,  alwaysHit: false, effect: null,
                  multiHit: { min: 2, max: 5, fixedDamage: 10 } },
  "바늘미사일": { power: 1,  type: "벌레", accuracy: 95,  alwaysHit: false, effect: null,
                  multiHit: { min: 2, max: 5, fixedDamage: 6 } },
  "사슬묶기":   { power: 0,  type: "노말", accuracy: 90,  alwaysHit: false, effect: null,
                  chainBind: true, targetSelf: false },
  "드래곤테일": { power: 40, type: "드래곤", accuracy: 90, alwaysHit: false, effect: null, dragonTail: true },
  "병상첨병":   { power: 50, type: "고스트", accuracy: 100, alwaysHit: false, effect: null, sickPower: true },
  "기사회생":   { power: 40, type: "격투",  accuracy: 100, alwaysHit: false, effect: null, reversal: true },
  "바둥바둥":   { power: 40, type: "노말",  accuracy: 100, alwaysHit: false, effect: null, reversal: true },
  "카운터":     { power: 1,  type: "격투",  accuracy: 100, alwaysHit: false, effect: null, counter: true },
  "버티기":     { power: 0,  type: "노말",  accuracy: 100, alwaysHit: true,  effect: null, endure: true, targetSelf: true },
  "객기":       { power: 50, type: "노말",  accuracy: 100, alwaysHit: false, effect: null, guts: true },
  "씨뿌리기":   { power: 0,  type: "풀",   accuracy: 90,  alwaysHit: false, effect: null, leechSeed: true, targetSelf: false },
  "치유파동":   { power: 0,  type: "에스퍼", accuracy: 100, alwaysHit: true, effect: null, healPulse: true, targetSelf: false },
  "참기":       { power: 0,  type: "노말",  accuracy: 100, alwaysHit: true,  effect: null, bide: true, targetSelf: true },
"엉겨붙기": { power: 20, type: "벌레", accuracy: 100, alwaysHit: false, effect: null, wrap: true },
"김밥말이": { power: 15, type: "노말", accuracy: 90,  alwaysHit: false, effect: null, wrap: true },
"소금물":   { power: 50, type: "물",   accuracy: 100, alwaysHit: false, effect: null, saltWater: true },
"트라이어택": { power: 50, type: "노말", accuracy: 100, alwaysHit: false,
                effect: { chance: 0.2, triAttack: true } },
"분함의발구르기": { power: 50, type: "땅", accuracy: 100, alwaysHit: false, effect: null, stomping: true },
"분풀이":   { power: 45, type: "악",   accuracy: 100, alwaysHit: false, effect: null, vengeance: true },
"물거품아리아": { power: 50, type: "물", accuracy: 100, alwaysHit: false, effect: { cureburn: true } },
"불사르기":     { power: 60, type: "불", accuracy: 100, alwaysHit: false, effect: null, burnOff: true },
"사이코노이즈": { power: 45, type: "에스퍼", accuracy: 100,
                  effect: { healBlock: true },
                  targetSelf: false, aoeEnemy: true },
"메테오빔":     { power: 70, type: "바위", accuracy: 90, alwaysHit: false, effect: null, meteorBeam: true },
"마지막일침":   { power: 40, type: "벌레", accuracy: 100, alwaysHit: false, effect: null, lastSting: true },
"거대해머":     { power: 70, type: "강철", accuracy: 100, alwaysHit: false, effect: null, heavyHammer: true },
"다이빙": { power: 50, type: "물", accuracy: 100, alwaysHit: false, effect: null, dive: true },
"예민해지기": { power: 0, type: "노말", accuracy: 100, alwaysHit: true, effect: null, focusEnergy: true, targetSelf: true },
}